- ext/gosu/extconf.rb
Hi maintainer :)
On my Mac, `sudo gem install gosu` fails like this:
```
Building native extensions.  This could take a while...
ERROR:  Error installing gosu:
ERROR: Failed to build gem native extension.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/gosu/gosu/wiki/Getting-Started-on-OS-X
creating Makefile
make "DESTDIR="
compiling stb_vorbis.c
error: -fobjc-arc is not supported on platforms using the legacy runtime
make: *** [stb_vorbis.o] Error 1
Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.8 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/gosu-0.10.8/ext/gosu/gem_make.out
```
I noticed that …
> Removed i386 architecture from ARCH_FLAG on Darwin

- .travis.yml
- Gosu/Version.hpp
- appveyor.yml
- ext/gosu/gosu.i
- ext/gosu/gosu_SWIG_RENAME_PATCH.patch
- lib/gosu/patches.rb
- rake/set_version.rb
- rdoc/gosu.rb
- src/RubyGosu.cxx
- src/Version.cpp
- windows/Gosu.vcxproj
- windows/Gosu.vcxproj.filters
It's a new year and I want to contribute more to the (ruby) community so I choose a (somewhat) random issue I thought wasn't that hard, but in fact I got some (maybe understanding) problems/questions.
I changed the Gosu/Version.hpp to use the constants defined in Gosu/Plattform.hpp to switch the version depending on the platform, but the ruby binding ist generated through swig which interprets the ifdef-else clause based on the platform of the system which calls rake swig. So I actually need to add the ifdef-else clase in the RubyGosu.cxx as well.
Now to the problem - is my understanding of the "problem" correct and if so - how to tell Swig (probably in ruby.i) to preserve the ifdef clause.
The commits in travis and appveyor are atm just for "testing" purposes as I found no real hint how …
> [WIP] Resolves #234 - Rework Gosu::VERSION and Gosu::LICENSES

- lib/gosu.rb
- lib/gosu/compat.rb
- lib/gosu/patches.rb
- lib/gosu/swig_patches.rb
- rdoc/gosu.rb
- test/test_constants.rb
- test/test_deprecations.rb
- test/test_interface.rb
I still have no idea how to safely deprecate constants and methods that have moved from one scope to another. This PR is a subset #370 that focuses on low-hanging fruit:
- Deprecate the Window constructors, this alone should be a good move for the Gosu ecosystem 👍 
- Deprecate `Window#set_mouse_position` and `Font#draw_rot`, which are always and clearly deprecated. (This is also a good time to remove them from rdoc.)
- Deprecate `Gosu::GOSU_COPYRIGHT_NOTICE` because I really want to deprecate at least one constant, and I (sadly...) doubt many people use this one, especially together with `include Gosu` - so this should be safe enough.
> Add deprecations to Ruby/Gosu (Resolves #367, subset of #370)

- Gosu.podspec
- Gosu/Fwd.hpp
- Gosu/Input.hpp
- Gosu/TextInput.hpp
- Gosu/Window.hpp
- examples/TextInput/CMakeLists.txt
- examples/TextInput/TextInput.cpp
- src/GosuAppDelegate.mm
- src/GosuGLView.cpp
- src/GosuGLView.hpp
- src/GosuViewController.cpp
- src/GosuViewController.hpp
- src/InputUIKit.cpp
- src/TextInput.cpp
- src/WindowUIKit.cpp
Implements UIKit support for TextInput (which must then be wrapped in motion-gosu for https://github.com/gosu/motion-gosu/issues/6).
> Add TextInput implementation for iOS/UIKit

- lib/gosu/compat.rb
Putting a space at the end of the URL will let terminals parse the link correctly, instead of opening a bad URL like "https://www.rubydoc.info/github/gosu/gosu/master/Gosu/Image.,"
> Tweak deprecation warnings so that URLs are accessible

- .travis.yml
Now that Homebrew has updated to SDL2 2.0.10, SDL2 fails to build on Xcode 7.x and Xcode 8.0 with the error "use of undeclared identifier 'NSEventSubtypeMouseEvent'", which is a symbol that was introduced in macOS Sierra. Building with Xcode 8.3, which has the Sierra SDK, fixes the issue. This is a regression introduced in SDL2 2.0.10 that will be fixed in SDL2 2.0.11. But until that is released and added to Homebrew, Travis just going to build every build.
- Update "old Mac" Travis build to use macOS Sierra with Xcode 8.3.3.
- Update "new Mac" Travis build to use the latest Travis image, which is macOS Mojave with Xcode 11.0.
- Don't `set -ev` in Travis as this fails the build on these new images.
See: https://travis-ci.org/gosu/gosu/jobs/583899519
See: …
> Use Xcode 8.3 and Xcode 11.0 on Travis CI

- src/Font.cpp
- src/LargeImageData.cpp
- src/Text.cpp
- src/TrueTypeFont.cpp
Gem fails to compile native extensions on GCC 10. This PR fixes that by including <stdexcept> in files that need it.
I tested this by successfully building the gem, installing it, and displaying a simple window on Fedora 32.
Fixes: https://github.com/gosu/gosu/issues/530
> Include <stdexcept> to fix compile errors on GCC 10.

- src/Input.cpp
If multiple gamepads are present at launch (and maybe if connected simultaneously) the first gamepad is opened again instead instead of the correct gamepad.
This causes the first gamepad to be "cloned" and screws up the `gamepad_slot` system.
Since the `Joystick Instance ID` is the same for the clones which is checked when removing a gamepad, this causes gamepads to be orphaned.
Cause: `e->jdevice.which` appears to always be `0` (SDL Device ID)
This PR eagerly tries to connect to every available gamepad when a new gamepad is connected, ignoring already connected gamepads.
> Fix multiple gamepads at launch

- Gosu/Audio.hpp
- ext/gosu/gosu.i
- rdoc/gosu.rb
- src/RubyGosu.cxx
Adds missing `Gosu.axis` to Ruby/Gosu swig interface
SWIG Also picked up `Gosu::Song#length` and `Gosu::Sample#length`
> Fix missing Gosu.axis

- CMakeLists.txt
- include/Gosu/Image.hpp
- rdoc/gosu.rb
- src/RubyGosu.cxx
* Makes some Image#draw arguments optional again, for compatibility with older games
* Don't set CMP0072, which was only introduced in CMake 3.11 (Gosu only requires 3.10); instead, confirm that we agree with all policy changes inbetween CMake 3.10 and 3.18.4: https://cmake.org/cmake/help/git-stage/command/cmake_policy.html#setting-policies-by-cmake-version
> Compatibility fixes

- CHANGELOG.md
- CMakeLists.txt
- Gosu.podspec
- examples/Tutorial-Touch/Podfile
- examples/Tutorial-Touch/Podfile.lock
- examples/Tutorial-Touch/Tutorial-Touch.xcodeproj/project.pbxproj
- examples/Tutorial/Podfile.lock
- ext/gosu/gosu.i
- ffi/Gosu.cpp
- ffi/Gosu.h
- ffi/Gosu_Constants.cpp
- ffi/Gosu_FFI_internal.h
- ffi/Gosu_Image.cpp
- ffi/Gosu_Window.cpp
- ffi/Gosu_Window.h
- include/Gosu/Version.hpp
- include/Gosu/Window.hpp
- lib/gosu/swig_patches.rb
- rdoc/gosu.rb
- src/Input.cpp
- src/Resolution.cpp
- src/RubyGosu.cxx
- src/RubyGosu.h
- src/TrueTypeFontWin.cpp
- src/Window.cpp
- src/WindowUIKit.cpp
- windows/GosuFFI.vcxproj
- windows/GosuFFI.vcxproj.filters
FYI @cyberarm this includes the WindowFlags / borderless changes from #555. I didn't want to merge the other parts without more time to actually test the changes on all platforms.
Due to the way I'm calling Window::set_resizable from the start of the constructor, this should also practically include the first fix from https://github.com/gosu/gosu/pull/541/files.
Bumped the version to 1.1.0 due to the large FFI-related changes in this PR and the previous ones.
> Window tweaks

- src/Macro.cpp
Instead of solving the lower right 2x2 subsystem iteratively using Gaussian Elimination, we can use the closed-form 2x2 matrix inverse to solve this part directly.
This avoids the branching based on certain cell values, which probably contains a bug: #571. This bug is fixed with this update.
> More robust solution of linear system in Macro::find_transform_for_target (fixes #571)

- ext/gosu/extconf.rb
- src/Resolution.cpp
- src/Window.cpp
- windows/Gosu.vcxproj
Move `pimpl->resizable = resizable` to above first call to `resize`. Fixes oversized windows becoming smaller.
Removed `min(width/height, max_width/height)`. May fix scaling weirdness. #497
> Possibly fix window scaling weirdness for resizable windows

- ffi/Gosu.cpp
- ffi/Gosu.h
- ffi/Gosu_Channel.cpp
- ffi/Gosu_Constants.cpp
- ffi/Gosu_FFI_internal.h
- ffi/Gosu_Font.cpp
- ffi/Gosu_Image.cpp
- ffi/Gosu_Sample.cpp
- ffi/Gosu_Song.cpp
- ffi/Gosu_TextInput.cpp
- ffi/Gosu_Window.cpp
- test/CMakeLists.txt
- test/FFITests.cpp
Rationale:
* For parity with SWIG Ruby/Gosu, ffi-gosu and gosu.cr need to throw helpful error messages when something goes wrong.
* The global Gosu_last_error() function should be easier to wrap than additional out parameters.
* For consistency, all Gosu_ functions (re)set the error, even ones like Gosu_milliseconds() which will hopefully never throw an exception.
* ...except Color functions. Too weird?
* There is only an error message right now. Adding a Gosu_last_error_type() function later should be easy, but Gosu itself does not really throw many interesting exception classes, mostly runtime_error and invalid_argument.
Downsides:
* Now even harmless functions like Gosu_milliseconds should technically be wrapped in Ruby for error processing :( ... but otherwise, this is going to be a …
> Add FFI error reporting

- ffi/Gosu.cpp
- ffi/Gosu.h
* Drop `_get_` from `Gosu_get_user_languages` FFI function (@jlnr Is `_get_` intended?)
* Fix possible crash if `Gosu.user_languages` returns nil by using Ruby's safe navigation operator
> User languages patches

- lib/gosu.rb
Ruby Installer's Ruby 3.1 changed the `RUBY_PLATFORM` string
See: https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html
> Fix Ruby 3.1 not adding DLL's to load path on Windows

- src/Audio.cpp
This fixes the major issues of #618 with the caveat that mojoAL's `AL_BUFFERS_QUEUED` may be returning an incorrect value, causing a song that has been stopped and had `play()` called will have garbage data from that previous run for the first-ish sample.
https://github.com/icculus/mojoAL/blob/42035035b4e5debb6fe30e475683da2c30e51326/mojoal.c#L3976-L3977
> Add call to alSourcei to Gosu::Song::Impl::stop() (ref: #618)

- ext/gosu/extconf.rb
Sometimes on an arm64 (apple silicon) mac, an old x86 homebrew with libsdl may exist in addition to the arm64 version of libsdl. This PR ensures that gosu is linked against the correct architecture even when both versions of libsdl exist. Previously the x86 will be favoured which resulted in a runtime error `symbol not found in flat namespace '_SDL_AtomicAdd'`
> Link to the correct libsdl on mac

- .clang-tidy
- ext/gosu/gosu.i
- include/Gosu/Input.hpp
- include/Gosu/TextInput.hpp
- include/Gosu/Timing.hpp
- include/Gosu/Window.hpp
- src/Audio.cpp
- src/AudioFileAudioToolbox.cpp
- src/AudioFileSDLSound.cpp
- src/BlockAllocator.cpp
- src/FileUnix.cpp
- src/FileWin.cpp
- src/Font.cpp
- src/Graphics.cpp
- src/Input.cpp
- src/InputUIKit.cpp
- src/Macro.cpp
- src/TextInput.cpp
- src/TimingApple.cpp
- src/TimingUnix.cpp
- src/TimingWin.cpp
- src/TrueTypeFont.cpp
- src/Window.cpp
- src/WindowUIKit.cpp
This fixes the changed sleeping behavior on Windows which was introduced by replacing the Win32 Sleep() function with std::chrono::sleep_for in #622.
> Fix sleeping bug

- src/Window.cpp
This completes the botched fix from 1.4.4, but still needs comments to explain why we don't use this_thread.
> Replace use of this_thread::sleep_for by Win32 Sleep()

- src/AudioFileSDLSound.cpp
- src/Input.cpp
Found another spot that needed to be patched
```
#0 15.96 compiling ../../src/Audio.cpp
#0 15.96 compiling ../../src/AudioFileAudioToolbox.cpp
#0 15.96 compiling ../../src/AudioFileSDLSound.cpp
#0 15.96 compiling ../../src/AudioImpl.cpp
#0 15.96 compiling ../../src/Bitmap.cpp
#0 15.96 compiling ../../src/BitmapIO.cpp
#0 15.96 compiling ../../src/BlockAllocator.cpp
#0 15.96 compiling ../../src/Channel.cpp
#0 15.96 compiling ../../src/Color.cpp
#0 15.96 compiling ../../src/DirectoriesApple.cpp
#0 15.96 compiling ../../src/DirectoriesUnix.cpp
#0 15.96 compiling ../../src/DirectoriesWin.cpp
#0 15.96 compiling ../../src/FileUnix.cpp
#0 15.96 ../../src/FileUnix.cpp: In member function ‘virtual void Gosu::File::resize(size_t)’:
#0 15.96 ../../src/FileUnix.cpp:76:14: warning: ignoring return …
```
> Fixes missing <stdexcept> header

- .github/workflows/cmake.yml
- src/Input.cpp
Use `SDL_GameControllerSetPlayerIndex` and `SDL_JoystickSetPlayerIndex` to have SDL set gamepad LED(s), refactored a bit to use the `event->jdevice.which` instead of iterating over known joysticks: fixes `wireless xbox 360 controller` from appearing twice if connected after program starts.
> This function is available since SDL 2.0.12.
> Use SDL_GameControllerSetPlayerIndex and SDL_JoystickSetPlayerIndex 

- .gitignore
- CMakeLists.txt
- cmake/GosuConfig.cmake.in
- examples/TextInput/CMakeLists.txt
- examples/Tutorial/CMakeLists.txt
- src/TexChunk.cpp
- src/Text.cpp
- test/CMakeLists.txt
Let's see if making Gosu non-SHARED breaks anything. The thing I don't quite understand is how the generated GosuTargets.cmake is supposed to find its dependencies.
> More CMake work (goal: make CLion's coverage reporting work)

- .clang-format
- ext/gosu/gosu.i
- include/Gosu/Bitmap.hpp
- include/Gosu/Color.hpp
- include/Gosu/Fwd.hpp
- include/Gosu/Gosu.hpp
- include/Gosu/Graphics.hpp
- include/Gosu/Image.hpp
- include/Gosu/Utility.hpp
- src/Bitmap.cpp
- src/BitmapIO.cpp
- src/Color.cpp
- src/Font.cpp
- src/Graphics.cpp
- src/Image.cpp
- src/Input.cpp
- src/LargeImageData.cpp
- src/Macro.cpp
- src/RubyGosu.cxx
- src/Utility.cpp
- test/.clang-format
- test/BitmapTests.cpp
- test/ColorTests.cpp
* Add more tests for Bitmap and Color, and improve some implementations.
* For example, Gosu::Color will now survive RGB->HSV->RGB round trips without rounding errors.
* The edges of most Gosu::Images should have slightly fewer dark artifacts.
* Align clang-format code style with WebKit. Revert over-eager conversion of () to {} for conversions.
> Refactor and test Bitmap and Color, introduce Gosu::Rect (C++ only)

- src/BinPacker.cpp
- src/BinPacker.hpp
- src/DrawOp.hpp
- src/Graphics.cpp
- src/TexChunk.cpp
- src/Texture.hpp
- src/Window.cpp
- test/DrawableTests.cpp
- test/ImageTests.cpp
I haven't spent much time thinking about multithreading in Gosu, but Ruby's garbage collector likes to free Gosu::Images from background threads, so this PR provides a minimal hotfix. (In practice, it means that Rubystein 3D now doesn't crash anymore.)
> Thread safety and TexChunk lifecycle fixes

- examples/TextInput/TextInput.cpp
- ffi/Gosu.cpp
- include/Gosu/Fwd.hpp
- include/Gosu/Graphics.hpp
- include/Gosu/Window.hpp
- src/GosuViewController.cpp
- src/Graphics.cpp
- src/GraphicsImpl.hpp
- src/Macro.cpp
- src/TexChunk.cpp
- src/Window.cpp
- src/WindowUIKit.cpp
- test/DrawableTests.cpp
- test/ImageTests.cpp
- test/TiledDrawableTests.cpp
This brings C++ Gosu more in line with Ruby/Gosu.
> Rename Gosu::Graphics to Gosu::Viewport, move static methods out of it

- src/Drawable.cpp
- src/GosuGLView.cpp
- src/Graphics.cpp
- src/OpenGLContext.cpp
- src/OpenGLContext.hpp
- src/Texture.cpp
- src/Window.cpp
- test/DrawableTests.cpp
The previous handling had several problems:
* The current context was never unset. This prevented other threads from making the shared context current when using Nvidia drivers under Linux.
* Sharing resources across multiple contexts seems to be pointless, at least from internet hearsay. I didn't notice a difference locally.
* Texture::~Texture() could actually throw, contrary to what its outdated comment said.
> Rework OpenGL context handling
